apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-api
  labels:
    app: prediction-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: prediction-api

  template:
    metadata:
      labels:
        app: prediction-api

    spec:
      # Comme dans les autres services pour uniformiser les permissions
      securityContext:
        runAsUser: 0
        #runAsGroup: 0
        fsGroup: 1000

      initContainers:
        - name: fix-permissions
          image: busybox:1.36
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              # On s'assure que le user 1000 a les droits sur le volume
              chown -R 1000:1000 /app/data /app/artifacts
              echo "✅ Volume nettoyé et droits fixés."
          volumeMounts:
            # IL FAUT MONTER LE VOLUME QUI CONTIENT .DVC ICI !
            - name: data
              mountPath: /app/data
            # Si .dvc est dans data ou un autre volume, il faut le monter
            - name: artifacts
              mountPath: /app/artifacts
          #volumeMounts: [] # Pas besoin de volume, c'est dans l'image

        # Attendre MLflow (car API charge les modèles)
        - name: wait-for-mlflow
          image: busybox:1.36
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              until wget -qO- http://mlflow:5000/health || true; do
                echo "⏳ Waiting for MLflow..."
                sleep 2
              done
              echo "✅ MLflow is ready"

      containers:
        - name: api
          image: docker.io/library/accidents_severity-api:1.0
          #imagePullPolicy: IfNotPresent
          # Configuration pour forcer l'utilisation de l'image locale
          imagePullPolicy: Never
          resources:
            limits:
              memory: "1Gi"
            requests:
              memory: "512Mi"
          #command: ["/bin/sh", "-c", "sleep 3600"]
          # On ignore tout ce qui est dans le Dockerfile (CMD/ENTRYPOINT) ça ça génère une erreur
          command: ["python3"]
          args: ["-m", "uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000", "--forwarded-allow-ips", "*"]
          workingDir: /app

          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: fastapi-config

            - secretRef:
                name: fastapi-secret

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 5

          volumeMounts:
            - name: data
              mountPath: /app/data

            - name: artifacts
              mountPath: /app/artifacts

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc

        - name: artifacts
          persistentVolumeClaim:
            claimName: mlflow-artifacts-pvc
