apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  labels:
    app: airflow-webserver
spec:
  replicas: 1

  selector:
    matchLabels:
      app: airflow-webserver

  template:
    metadata:
      labels:
        app: airflow-webserver

    spec:
      # Comme dans le deployment de mlflow pour s'assurer des droits identiques partout
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000

      initContainers:
        - name: wait-for-postgres
          image: postgres:16.13-trixie
          imagePullPolicy: IfNotPresent

          command:
            - sh
            - -c
            - |
              until pg_isready -h postgres -p 5432 -U airflow; do
                echo "⏳ Waiting for postgres..."
                sleep 2
              done
              echo "✅ Postgres is ready"

      containers:
        - name: git-sync
          image: registry.k8s.io/git-sync/git-sync:v4.1.0
          imagePullPolicy: IfNotPresent

          envFrom:
            - configMapRef:
                name: airflow-gitsync-config

          volumeMounts:
            - name: airflow-git-repo
              # Répertoire de travail du container GitSync
              mountPath: /git

        - name: webserver
          image: docker.io/library/accidents_severity-airflow:1.0
          # Si absente alors on l'a récupère sur le docker hub
          # Evolution dans un env de prod: mettre en place le sytème
          # pour récupérer l'image
          #imagePullPolicy: IfNotPresent
          # Configuration pour forcer l'utilisation de l'image locale
          imagePullPolicy: Never

          command: ["bash", "-c"]
          args:
            - airflow webserver

          ports:
            - containerPort: 8080

          # Contient la configuration commune à plusieurs pods
          envFrom:
            - configMapRef:
                name: airflow-config
            - secretRef:
                name: airflow-secret

          # Contient la configuration spécifique à ce pods
          env:
            - name: AIRFLOW__WEBSERVER__PORT
              value: "8080"

          startupProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 10
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 10
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 10
            failureThreshold: 5

          volumeMounts:
            - name: airflow-git-repo
              # Répertoire de travail du container GitSync
              # Les volumes dags et plugins sont présent
              # grâce aux variables settées dans configmap.yaml
              mountPath: /git
            - name: logs
              mountPath: /opt/airflow/logs

      volumes:
        - name: airflow-git-repo
          # Volume via GitSync container
          emptyDir: {}

        - name: logs
          persistentVolumeClaim:
            claimName: airflow-pvc-logs
