apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yml=../../monitoring/prometheus/prometheus.yml

  - name: prometheus-rules
    files:
      - alert_rules.yml=../../monitoring/prometheus/rules/alert_rules.yml

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
