apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-pvc-logs
spec:
  storageClassName: "local-path"
  accessModes:
    # En mode local-path, prévu que pour un seul noeud (la VM)
    - ReadWriteOnce
    # En mode longhorn (ou autre), adapté pour plusieurs noeuds mais la VM a un disk et ram to petit pour supporter le volume
    #- ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dvc-state-pvc
spec:
  storageClassName: "local-path"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
