apiVersion: apps/v1
kind: Deployment

# Mêmes commentaires que dans postgres
metadata:
  name: redis
  labels:
    app: redis

spec:
  replicas: 1

  selector:
    matchLabels:
      app: redis

  template:
    metadata:
      labels:
        app: redis

    spec:
      containers:
        - name: redis
          image: redis:7
          imagePullPolicy: IfNotPresent

          resources:
            # Le request réserve physiquement la mémoire
            # Le request vérifie que le CPU restant >= cpu sinon il ne démarre pas le pod
            # d'où la faible valeur car on a bcp de services
            requests:
              memory: "128Mi" # Ce qu'il demande au démarrage
              cpu: "50m"      # 0.05 vCPU
            limits:
              memory: "1Gi"   # Le plafond à ne pas dépasser
              cpu: "1000m"    # 1.0 vCPU maximum

          ports:
            - containerPort: 6379

          # On lance la commande redis-server --save "" --appendonly no
          args:
            # nom de la commande suivi de ces 2 arguments (souvent déjà fourni par l'image officielle)
            - redis-server
            # désactive les snapshots RDB (sauvegarde périodique sur disque)
            - --save ""
            # désactive le journal AOF
            - --appendonly no

          startupProbe:
            exec:
              command: ["redis-cli", "ping"]
            periodSeconds: 10
            failureThreshold: 30

          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            periodSeconds: 10
            failureThreshold: 10

          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            periodSeconds: 10
            failureThreshold: 3
