# Makefile (version ed02) à la racine Template_MLOps_accidents

# ==========================================
# --- CONFIGURATION GLOBALE (Directives) ---
# ==========================================
# Sur Ubuntu, /bin/sh pointe vers dash ultra-rapide et léger, mais il est très "strict
# Selon les machines, /bin/sh peut aussi pointer autre part
# Comme /bin/bash est beaucoup plus puissant que dash. On va l'utiliser par défaut.
# et ainsi on garantit le même fonctionnement quelque soit la machine
# Doit être la 1ème ligne de commande
SHELL := /bin/bash

# Indiquer que ces cibles ne sont pas des fichiers
.PHONY: help upgrade-docker-tools setup-permissions install
.PHONY: setup-ci quality push
.PHONY: docker_prod_or_debug docker-FullClean-full-build
.PHONY: docker_service_full_check-health docker_check_port_routage docker_check_port_free docker_ssl_prep docker-reset-for-full-simu
.PHONY: docker-full-start-WoInitialTrain_fast
.PHONY: drift-on drift-off
.PHONY: docker-stop docker-down docker-status
.PHONY: ubuntu_usage docker-disks-storage docker-shell-mlflow docker-shell-postgres db-psql-postgres-data db-psql-postgres-disk
.PHONY: variables test-variables


# Raccourci : taper juste "make" lancera la liste des commandes du Makefile
.DEFAULT_GOAL := help

# ========================================
# --- VARIABLES (Paramètres du Projet) ---
# ========================================

# On l'utilise aussi dans le champs name défini au début de docker_compose.yml
# L'export permet de le rendre visible à tous
# Préféré à l'ajout de la variable dans .env qui est souvent écrasé
export PROJECT_NAME=accidents_severity
export DAGSHUB_REPO_NAME=Template_MLOps_accidents
#export _AIRFLOW_WWW_USER_USERNAME=admin
#export _AIRFLOW_WWW_USER_PASSWORD=admin

# On récupère l'IP publique de la machine actuelle
export PROJECT_IP=$(shell curl -s ifconfig.me)

# Extraction de la version (ex: transforme "3.12.1" en "py312")
# Utilisé pour la commande black dans la cible quality
# le fichier .python-version contient la version python utilisée
PY_VERSION := py$(shell cat .python-version | cut -d'.' -f1,2 | tr -d '.')

# ex: make all MSG="Upd periodic" et = msg de commit par défaut si on oublie de le préciser
# ? permet d'assigner de façon conditionnelle uniquement si MSG n'est pas défini dans une commande
# DANS LE make xxx MSG="yyy" ON DOIT METTRE LES ""
# Mais pour la variable surtout pas sinon le git commit -m "$(MSG)" || @echo "Rien à commiter"
# plante car il y aura ""xxxx"" et donc inohérent
MSG ?= Mise à jour automatique du pipeline
# DAGSHUB_USER ?= sage-flfay # devient inutile car fait dans le setup_dagshub_key.sh

# Définition du chemin pour uv (sinon pb avec Makefile qui perd uv à la ligne suivante)
# NB: := affectation immédiate du chemin explicite dans la variable;
#     =  affectation récursive; la formule est stocké en brut et recalculée à chaque utilisation
# ON ASSIGNE DE FAçON DEFINITIVE (LE :)
UV_PATH := $(HOME)/.local/bin
UV_BIN := $(UV_PATH)/uv

# Pour utiliser uv au lieu de $(UV_BIN) uniquement dans le MakeFile.
# Avantage: pour la cible "pipeline:" en faisant uv run dvc repro, 
# dvc.yaml en hérite mais uniquement dans ce cas. Donc on rajoute UV_PATH au PATH
export PATH := $(UV_PATH):$(PATH)
# NB: Chaque ligne de commande est vue comme un Shell (avec ".ONESHELL:" présent, c'est pour chaque cible)
# Ainsi, après import de uv, on passe à la ligne de commande suivante ET l'export PATH, lui,
# est réinjecté par Make dans chaque nouveau Shell qu'il ouvre <=> donc pour chaque nouvelle ligne commande

# On récupère les identifiants utilisateurs
export USER_ID := $(shell id -u)
export GROUP_ID := $(shell id -g)

# EXPORT pour que docker compose y ait accès pour les services Airflow
export AIRFLOW_UID := $(USER_ID)
# Le groupe root de l'image Airflow (explication à 0 dans le docker-compose)
export AIRFLOW_GID := 0

REPO := Template_MLOps_accidents
CUR_DIR := $(HOME)/$(REPO)

# Chemin absolu du fichier Makefile
# ROOT_DIR := $(shell dirname $(realpath $(lastword $(MAKEFILE_LIST))))
# Inutilisé pour le moment mais gardé au cas où!!

# ========================================
# VARIABLES MLFLOW
# 0.0.0.0 pour écouter tout le monde
# ========================================
MLFLOW_HOST = 0.0.0.0
MLFLOW_PORT = 5000

# ==============================================
# Pour le script Python (train_model.py),
# on utilise localhost car il est sur la même VM
# ==============================================

# Pour les tests en direct sur Ubuntu (ex: python src/models/train_model.py)
export MLFLOW_TRACKING_URI=http://localhost:$(MLFLOW_PORT)

# Pour l'injection dans les containers Docker.
# WARNING: dans docker-compose.yml verifier que pour le service mlflow
# on a bien container_name: mlflow_server
export DOCKER_MLFLOW_TRACKING_URI=http://mlflow_server:$(MLFLOW_PORT)

# =======================================================
# VARIABLES POUR NGINX (port extérieur (out) et fichiers)
# =======================================================
# NGINX_PORT_OUT = 9999

# ========================================
# CONFIGURATION SECURITE SSL
# ========================================
CERT_DIR = deployments/nginx/certs


# ========================================
# POUR UPGRADE DOCKER COMPOSE, BUILDX
# ========================================
# Version cible validée sur ton autre machine
TARGET_COMPOSE_VERSION := v2.39.1
TARGET_BUILDX_VERSION  := v0.26.1

# Chemins des plugins (Standard Docker)
PLUGINS_DIR  := $(HOME)/.docker/cli-plugins
COMPOSE_PATH := $(PLUGINS_DIR)/docker-compose
BUILDX_PATH  := $(PLUGINS_DIR)/docker-buildx

# URLs de téléchargement
COMPOSE_URL := https://github.com/docker/compose/releases/download/$(TARGET_COMPOSE_VERSION)/docker-compose-linux-x86_64
BUILDX_URL  := https://github.com/docker/buildx/releases/download/$(TARGET_BUILDX_VERSION)/buildx-$(TARGET_BUILDX_VERSION).linux-amd64


# ========================================
# POUR EVIDENTLY
# ========================================
export EVIDENTLY_PATH := /app/data/evidently
export WORKSPACE_NAME := ${PROJECT_NAME}-ws
export EVIDENTLY_WORKSPACE := ${EVIDENTLY_PATH}/${WORKSPACE_NAME}
# Définition des répertoires dans la VM
DATA_EVIDENTLY_VM_DIRS := data/users \
			  data/mlruns_latest \
			  data/evidently/reports \
			  data/evidently/$(WORKSPACE_NAME)

# ====================================================
# POUR LANCER ET TESTER LES SERVICES VIA DOCKER COMPOSE
# ====================================================
# Liste des services indépendants
INDEPENDANT_SERVICES = postgres redis prometheus
# On remplace l'espace par une barre verticale pour le test du healtcheck
INDEPENDANT_SERVICES_REGEX = $(shell echo "$(INDEPENDANT_SERVICES)" | tr ' ' '|')
# Nombre de web services
INDEPENDANT_SERVICES_NUM = $(words $(INDEPENDANT_SERVICES))

# Liste des services dépendants
DEPENDANT_SERVICES = api mlflow airflow-webserver airflow-scheduler airflow-worker airflow-flower grafana node-exporter cadvisor evidently_ui monitoring
# On remplace l'espace par une barre verticale pour le test du healtcheck
DEPENDANT_SERVICES_REGEX = $(shell echo "$(DEPENDANT_SERVICES)" | tr ' ' '|')
# Nombre de web services
DEPENDANT_SERVICES_NUM = $(words $(DEPENDANT_SERVICES))

# =====================================
# --- LISTE DES COMMANDES AVEC MAKE ---
# =====================================
help: ## [HELP] Affiche la liste des toutes les commandes disponibles (help exécuté par défaut)
	@echo "🛠️  MENU D'AIDE - COMMANDES DISPONIBLES"
	@echo "------------------------------------------------------------------------------------------------------------------"
	@# 1. On cherche les lignes débutant par le nom d'une cible (Lettres, Tirets, Underscores)
	@# 2. On s'assure qu'elles se terminent par ':' (syntaxe Makefile)
	@# 3. On extrait le commentaire situé après le marqueur '##'
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | \
		 awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'
	@echo "------------------------------------------------------------------------------------------------------------------"


# ===================================================================================
# --- VERIFICATION / INSTALLATION DOCKER COMPOSE VERSION v2.39.1 ET BUILDX 0.26.1 ---
# ===================================================================================
upgrade-docker-tools:
	@mkdir -p $(PLUGINS_DIR)

	@echo "🛠️  Vérification de Docker Compose..."
	@CURRENT_V_COMPOSE=$$(docker compose version --short 2>/dev/null || echo "none"); \
	if [ "$$CURRENT_V_COMPOSE" != "$(TARGET_COMPOSE_VERSION)" ]; then \
		echo "🚀 Installation de Compose $(TARGET_COMPOSE_VERSION)..."; \
		curl -SL $(COMPOSE_URL) -o $(COMPOSE_PATH); \
		chmod +x $(COMPOSE_PATH); \
		echo "✅ Docker Compose mis à jour : $(TARGET_COMPOSE_VERSION)"; \
	else \
		echo "✅ Docker Compose est déjà à jour ($$CURRENT_V_COMPOSE)."; \
	fi

	@echo "🛠️  Vérification de Buildx..."
	@CURRENT_V_BUILDX=$$(docker buildx version 2>/dev/null | cut -d' ' -f2 || echo "none"); \
	if [[ "$$CURRENT_V_BUILDX" != *"$(TARGET_BUILDX_VERSION)"* ]]; then \
		echo "🚀 Installation de Buildx $(TARGET_BUILDX_VERSION)..."; \
		curl -SL $(BUILDX_URL) -o $(BUILDX_PATH); \
		chmod +x $(BUILDX_PATH); \
		echo "✅ Buildx mis à jour : $(TARGET_BUILDX_VERSION)"; \
	else \
		echo "✅ Buildx est déjà à jour ($$CURRENT_V_BUILDX)."; \
	fi

# ===================================================================================
# --- VERIFICATION / INSTALLATION DOCKER COMPOSE VERSION v2.39.1 ET BUILDX 0.26.1 ---
# ===================================================================================
setup-permissions:
	@echo "🔐 Restauration de la propriété pour UID $(USER_ID):GID $(GROUP_ID) dans tout le répertoire à partir de la racine (le .)"
	@sudo chown -R $(USER_ID):$(GROUP_ID) .
	@echo "✅ Propriété restaurée avec succès."

# =================================================
# --- SETUP COMPLET (À lancer la première fois) ---
# =================================================
# NB: ne jamais mettre de commentaire après \ car génère une erreur
# @ devant une commande (ex: @if) pour que la commande ne soit pas affichée
# Pour les if comme on a déjà @if, la commande echo "xxx" n'est donc pas affichée et donc pas de risque d'avoir le message affiché 2 fois

install: ## [INIT] Installation/Initialisation complète du projet
	@# ******************************************************************************************************
	@# 0. Vérification des clés et code secrets dans le make (Priorité n°1) É
	@# ******************************************************************************************************

	@$(MAKE) -s setup-permissions

	@if [ -z "$(DAGSHUB_S3_ACCESS_KEY_ID)" ] || [ -z "$(DAGSHUB_S3_SECRET_ACCESS_KEY)" ]; then \
		echo "--------------------------------------------------------------------------------------------"; \
		echo "❌ ERREUR : Clés DagsHub manquantes !"; \
		echo "🛡️ PAR SÉCURITÉ, LES CLÉS SONT DANS LE .BASHRC AU LIEU DE .ENV (ANTICIPER .ENV ENVOYÉ SUR GITHUB PAR FAUSSE MANIP) !"; \
		echo "💡 SUR LE TERMINAL, "; \
		echo "   1. LANCER LE SCRIPT POUR UPDATER .BASHRC: ./setup_dagshub_key.sh ET LAISSEZ-VOUS GUIDER"; \
		echo "   2. REACTUALISER L'ENVIRONNEMENT: source ~/.bashrc"; \
		echo "   WARNING: Si étape 2. est omise, vous retomber sur l'erreur. SOLUTION retaper la commande: source ~/.bashrc"; \
		echo "ℹ️ setup_dagshub_key.sh peut être rejoué plusieurs fois car s'il détecte la présence des variables, alors il ne fait rien"; \
		echo ""; \
		echo "*****************************************************************************************************"; \
		echo "💥💥💥 UNE FOIS LES VARIABLES MISES À JOUR, RELANCER IMPÉRATIVEMENT LE MAKEFILE AVEC LE MÊME SCRIPT !"; \
		echo "*****************************************************************************************************"; \
		echo ""; \
		exit 1; \
	fi
	@echo "✅ Clés DagsHub détectées avec succès et activées !"

	@# **************************************************************************************************************
	@# 0.bis Vérification du contenu du fichier daemon.json utilisé par le service cadvisor pour le dahsboard grafana
	@# **************************************************************************************************************

	@echo "--- Vérification de la configuration Docker metrics (/etc/docker/daemon.json) ---"
	@if [ ! -f /etc/docker/daemon.json ]; then \
		echo "Fichier inexistant. Création..."; \
		sudo mkdir -p /etc/docker; \
		echo '{"metrics-addr":"0.0.0.0:9323","experimental":true}' | sudo tee /etc/docker/daemon.json > /dev/null; \
		echo "On redémarre le docker pour prendre en compte le fichier daemon.json"; \
		sudo systemctl restart docker; \
		echo "✅ Configuration Docker metrics effectué avec succès (/etc/docker/daemon.json correctement setté) !"; \
		echo ""; \
	elif grep -q "metrics-addr" /etc/docker/daemon.json; then \
		echo "✅ Docker metrics déjà configuré. /etc/docker/daemon.json correctement setté"; \
		echo ""; \
	else \
		echo "Configuration absente dans daemon.json existant. Sauvegarde et mise à jour..."; \
		echo "Sauvegarde du fichier original /etc/docker/daemon.json.bak"; \
		echo ""; \
		sudo cp /etc/docker/daemon.json /etc/docker/daemon.json.bak; \
		sudo sed -i 's/}/, "metrics-addr":"0.0.0.0:9323", "experimental":true}/' /etc/docker/daemon.json; \
		echo "On redémarre le docker pour prendre en compte le fichier daemon.json"; \
		sudo systemctl restart docker; \
		echo "✅ Configuration Docker metrics effectué avec succès (/etc/docker/daemon.json correctement setté) !"; \
		echo ""; \
	fi

	@# ******************************************************************************************************
	@# 1. Installation de uv si absent
	@# ******************************************************************************************************

	@if [ ! -f $(UV_BIN) ]; then \
		echo "🚀 Installation de uv..."; \
		curl -LsSf https://astral.sh/uv/install.sh | sh; \
	else \
		echo "✅ uv est déjà installé."; \
	fi

	@echo "Vérification de la version"
	uv --version

	@# ******************************************************************************************************
	@# 1bis. Vérification / Installation des docker tools
	@# ******************************************************************************************************

	@$(MAKE) -s upgrade-docker-tools

	@# ******************************************************************************************************
	@# 2. Création du .venv si absent
	@# ******************************************************************************************************

	@if [ ! -d ".venv" ]; then \
		echo "🌱 Création de l'environnement virtuel (.venv)..."; \
		uv venv; \
	fi

	@# ******************************************************************************************************
	@# 3. Gestion des dépendances
	@# ******************************************************************************************************

	@# 3.1 : Migration (Si absent, on le crée à partir du .txt)
	@# NB: grep -vE '^\s*#|^-e|^\s*$$'
	@#   -vE : exclut toutes les lignes qui correspondent à :
	@#     ^\s*# : commence par # (avec ou sans espaces avant) -> commentaires
	@#     ^-e   : commence par -e -> installation locale éditable
	@#     ^\s*$$ : ligne vide
	@# uv init --lib --no-readme :
	@#     uv init : crée le fichier pyproject.toml;
	@#     --lib : crée si nécessaire __init__.py dans chaque dossier
	@#             = projet configuré comme une bibliothèque (ou un package structuré).
	@#     --no-readme : ne pas créer README.md
	@# uv add : remplit le pyproject.toml ET génère le uv.lock initial
	@# exclusion de -e . dans le grep pour éviter risque conflit de syntaxe de uv add
	@# uv pip install -e . : pour installer le projet en mode éditable (cf requirements.txt pour explication)

	@echo ""
	@echo "======================================================"
	@echo "🐍 VERSION PYTHON UTILISÉE : $$(cat .python-version)"
	@echo "======================================================"
	@echo ""

	@if [ ! -f pyproject.toml ] && [ -f requirements.txt ]; then \
		eu du fichier daemon.json utilisé par le service cadvisor pour le dahsboard grafana
	@# **************************************************************************************************************

	@echo "--- Vérification de la configuration Docker metrics (/etc/docker/daemon.json) ---"
	@if [ ! -f /etc/docker/daemon.json ]; then \
		echo "Fichier inexistant. Création..."; \
		sudo mkdir -p /etc/docker; \
		echo '{"metrics-addr":"0.0.0.0:9323","experimental":true}' | sudo tee /etc/docker/daemon.json > /dev/null; \
		echo "On redémarre le docker pour prendre en compte le fichier daemon.json"; \
		sudo systemctl restart docker; \
		echo "✅ Configuration Docker metrics effectué avec succès (/etc/docker/daemon.json correctement setté) !"; \
		echo ""; \
	elif grep -q "metrics-addr" /etc/docker/daemon.json; then \
		echo "✅ Docker metrics déjà configuré. /etc/docker/daemon.json correctement setté"; \
		echo ""; \
	else \
		echo "Configuration absente dans daemon.json existant. Sauvegarde et mise à jour..."; \
		echo "Sauvegarde du fichier original /etc/docker/daemon.json.bak"; \
		echo ""; \
		sudo cp /etc/docker/daemon.json /etc/docker/daemon.json.bak; \
		sudo sed -i 's/}/, "metrics-addr":"0.0.0.0:9323", "experimental":true}/' /etc/docker/daemon.json; \
		echo "On redémarre le docker pour prendre en compte le fichier daemon.json"; \
		sudo systemctl restart docker; \
		echo "✅ Configuration Docker metrics effectué avec succès (/etc/docker/daemon.json correctement setté) !"; \
		echo ""; \
	fi

	@# ******************************************************************************************************
	@# 1. Installation de uv si absent
	@# ******************************************************************************************************

	@if [ ! -f $(UV_BIN) ]; then \
		echo "🚀 Installation de uv..."; \
		curl -LsSf https://astral.sh/uv/install.sh | sh; \
	else \
		echo "✅ uv est déjà installé."; \
	fi

	@echo "Vérification de la version"
	uv --version

	@# ******************************************************************************************************
	@# 1bis. Vérification / Installation des docker tools
	@# ******************************************************************************************************

	@$(MAKE) -s upgrade-docker-tools

	@# ******************************************************************************************************
	@# 2. Création du .venv si absent
	@# ******************************************************************************************************

	@if [ ! -d ".venv" ]; then \
		echo "🌱 Création de l'environnement virtuel (.venv)..."; \
		uv venv; \
	fi

	@# ******************************************************************************************************
	@# 3. Gestion des dépendances
	@# ******************************************************************************************************

	@# 3.1 : Migration (Si absent, on le crée à partir du .txt)
	@# NB: grep -vE '^\s*#|^-e|^\s*$$'
	@#   -vE : exclut toutes les lignes qui correspondent à :
	@#     ^\s*# : commence par # (avec ou sans espaces avant) -> commentaires
	@#     ^-e   : commence par -e -> installation locale éditable
	@#     ^\s*$$ : ligne vide
	@# uv init --lib --no-readme :
	@#     uv init : crée le fichier pyproject.toml;
	@#     --lib : crée si nécessaire __init__.py dans chaque dossier
	@#             = projet configuré comme une bibliothèque (ou un package structuré).
	@#     --no-readme : ne pas créer README.md
	@# uv add : remplit le pyproject.toml ET génère le uv.lock initial
	@# exclusion de -e . dans le grep pour éviter risque conflit de syntaxe de uv add
	@# uv pip install -e . : pour installer le projet en mode éditable (cf requirements.txt pour explication)

	@echo ""
	@echo "======================================================"
	@echo "🐍 VERSION PYTHON UTILISÉE : $$(cat .python-version)"
	@echo "======================================================"
	@echo ""

	@if [ ! -f pyproject.toml ] && [ -f requirements.txt ]; then \
		e