apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# On indique dans quel namespace déployer ses ressources
namespace: accidents-severity

resources:
  - namespace.yaml
  - base/postgres
  - base/redis
  - base/mlflow
  - base/airflow
  - base/jobs
  - base/fastapi
  - base/prometheus
  - base/grafana
  - base/node-exporter
  - base/cadvisor
  - base/evidently
  - base/ingress
