apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Le name du Generator contient la racine fournie plus l'extension hash -xxxx
# Ainsi, dès qu'une modification est faite dans le .env.config ou .env.secret,
# comme le hash change, le/les pods concernés sot automatiquement réinitialisés
# L'inconvénient est qu'on peut seulement les utiliser dans les autres répertoires
# avec name-hash. Avec cette option, on disable le hash et ainsi on peut l'utiliser
# partour dans le projet. L'inconvénient est que si modifie le config ou secret,
# on doit réinitialiser manuellement. Mais au moins on sait que la modification
# sera vu de tous après le reset de tous les pods
generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: grafana-config
    envs:
      - .env.config

  - name: grafana-datasources
    files:
      - provisioning/datasources/datasource.yml

  - name: grafana-dashboard-provider
    files:
      - provisioning/dashboards/dashboard.yml

  - name: grafana-alerting
    files:
      - provisioning/alerting/alert_drift.yaml
      - provisioning/alerting/contact_points.yaml
      - provisioning/alerting/notification_policies.yaml

  # Supprimés car trop gros en taille et ne passe pas lors du kubectl apply -k k8s/
  #- name: grafana-dashboards
  #  files:
  #    - dashboards_json/VMusage-dashboard.json
  #    - dashboards_json/accidents-dashboard.json
  #    - dashboards_json/containers-dashboard.json

resources:
  - pvc.yaml
  - service.yaml
  - ingress.yaml
  - deployment.yaml
