apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-api
  labels:
    app: prediction-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: prediction-api

  template:
    metadata:
      labels:
        app: prediction-api

    spec:
      # Comme dans les autres services pour uniformiser les permissions
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000

      initContainers:
        # Attendre MLflow (car API charge les modèles)
        - name: wait-for-mlflow
          image: busybox
          imagePullPolicy: IfNotPresent

          command:
            - sh
            - -c
            - |
              until wget -qO- http://mlflow:5000/health || true; do
                echo "⏳ Waiting for MLflow..."
                sleep 2
              done
              echo "✅ MLflow is ready"

      containers:
        - name: api
          image: accidents_severity-api:1.0
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
              name: fastapi-config

            - secretRef:
              name: fastapi-secret

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 5

          volumeMounts:
            - name: data
              mountPath: /app/data

            - name: artifacts
              mountPath: /app/artifacts

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc

        - name: artifacts
          persistentVolumeClaim:
            claimName: mlflow-artifacts-pvc
