apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-api
  labels:
    app: prediction-api

spec:
  replicas: 1

  selector:
    matchLabels:
      app: prediction-api

  template:
    metadata:
      labels:
        app: prediction-api

    spec:
      # Comme dans les autres services pour uniformiser les permissions
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000

      initContainers:
        # Attendre MLflow (car API charge les modèles)
        - name: wait-for-mlflow
          image: busybox
          command:
            - sh
            - -c
            - |
              until wget -qO- http://mlflow:5000/health || true; do
                echo "⏳ Waiting for MLflow..."
                sleep 2
              done
              echo "✅ MLflow is ready"

      containers:
        - name: api
          image: accidents_severity-api:1.0
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000

          env:
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow:5000"

            - name: UV_LINK_MODE
              value: "copy"

            - name: GIT_PYTHON_REFRESH
              value: "quiet"

            - name: DAGSHUB_REPO_NAME
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: DAGSHUB_REPO_NAME

            - name: DAGSHUB_USER
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: DAGSHUB_USER

            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: AWS_ACCESS_KEY_ID

            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: AWS_SECRET_ACCESS_KEY

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 20
            failureThreshold: 5

          volumeMounts:
            - name: data
              mountPath: /app/data

            - name: artifacts
              mountPath: /app/artifacts

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc

        - name: artifacts
          persistentVolumeClaim:
            claimName: mlflow-artifacts-pvc
