{
 "title": "Containers Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "POD CPU USAGE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"accidents-severity\",container!=\"\",pod!=\"\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "POD RAM USAGE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"accidents-severity\",container!=\"\",pod!=\"\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "POD NETWORK RX VOLUME",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"accidents-severity\",pod!=\"\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}