apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "evidently-pvc"

spec:
  accessModes:
    - ReadWriteOnce

  # optionnel selon le cluster
  storageClassName: "local-path"

  resources:
    requests:
      storage: 1Gi
