apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evidently-pvc

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi

  # optionnel selon le cluster
  storageClassName: standard
