apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
# Opaque car Kubernetes ne connaît pas le sens métier (l'utilité) de ces données (boite fourre-tout)
type: Opaque
# stringData permet d'écrire les valeurs en clair (airflow)
# Kubernetes les convertit automatiquement en base64 dans etcd
# Sans stringData (donc remplacé par data) il faudrait fournir directement
# des valeurs encodées en base64 avec echo -n "airflow" | base64 → YWlyZmxvdw==
stringData:
  POSTGRES_DB: airflow
  POSTGRES_USER: airflow
  POSTGRES_PASSWORD: airflow
