apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: grafana-config
    envs:
      - .env.config

  - name: grafana-datasources
    files:
      - datasource.yml=../../monitoring/grafana/provisioning/datasources/datasource.yml

  - name: grafana-dashboard-provider
    files:
      - dashboard.yml=../../monitoring/grafana/provisioning/dashboards/dashboard.yml

  - name: grafana-alerting
    files:
      - alert_drift.yaml=../../monitoring/grafana/provisioning/alerting/alert_drift.yaml
      - contact_points.yaml=../../monitoring/grafana/provisioning/alerting/contact_points.yaml
      - notification_policies.yaml=../../monitoring/grafana/provisioning/alerting/notification_policies.yaml

  - name: grafana-dashboards
    files:
      - VMusage-dashboard.json=../../monitoring/grafana/dashboards_json/VMusage-dashboard.json
      - accidents-dashboard.json=../../monitoring/grafana/dashboards_json/accidents-dashboard.json
      - containers-dashboard.json=../../monitoring/grafana/dashboards_json/containers-dashboard.json

resources:
  - pvc.yaml
  - service.yaml
  - deployment.yaml
