apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config

data:
  # inutile car j'ai mis .env.config dans le kustomization
  #PROJECT_NAME: "accidents-severity"
  #DOCKER_MLFLOW_TRACKING_URI: "http://mlflow_server:5000"
  #DAGSHUB_REPO_NAME: "Template_MLOps_accidents"

  # --- Mlflow ---
  MLFLOW_TRACKING_URI: ${DOCKER_MLFLOW_TRACKING_URI}
  MLFLOW_EXPERIMENT_NAME: ${PROJECT_NAME}


  # --- Airflow core ---
  AIRFLOW__CORE__EXECUTOR: "CeleryExecutor"
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  AIRFLOW__CORE__HOSTNAME_CALLABLE: "socket.gethostname"
  # GIT_SYNC_DEST = mlops_accidents_k3s ce qui permet d'avoir la même arborescence que sur github
  AIRFLOW__CORE__DAGS_FOLDER: "/git/mlops_accidents_k3s/deployments/airflow/dags"
  AIRFLOW__CORE__PLUGINS_FOLDER: "/git/mlops_accidents_k3s/deployments/airflow/plugins"
  # Relecture des dags toutes les 30s
  AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL=30

  # --- Celery / Redis ---
  AIRFLOW__CELERY__BROKER_URL: "redis://redis:6379/0"

  # --- Webserver ---
  AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: "true"
  AIRFLOW__WEBSERVER__BASE_URL: "http://localhost/airflow"
  AIRFLOW__WEBSERVER__RATELIMIT_STORAGE_URI: "redis://redis:6379/0"

  # --- API ---
  AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session"

  # --- DVC ---
  DVC_REMOTE: "origin"

  # --- DAGSHUG ---
  DAGSHUB_REPO_NAME: ${DAGSHUB_REPO_NAME}
  AWS_ENDPOINT_URL: "https://dagshub.com/s3"
