apiVersion: v1
kind: Secret
metadata:
  name: airflow-secret

# Les variables sotn dans .env.secret présent dans kustomization
stringData:
  # ici airflow:airflow sont des identifiants de connexion
  # --- Database ---
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@postgres:5432/airflow"
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@postgres:5432/airflow"
  AIRFLOW_CONN_POSTGRES_DEFAULT="postgres://airflow:airflow@postgres:5432/airflow"

  # --- Celery / Redis ---
  AIRFLOW__CELERY__RESULT_BACKEND: "db+postgresql://airflow:airflow@postgres:5432/airflow"

  # --- Airflow core ---
  AIRFLOW__CORE__FERNET_KEY=${AIRFLOW_FERNET_KEY}

  # --- Webserver ---
  _AIRFLOW_WWW_USER_USERNAME: "${_AIRFLOW_WWW_USER_USERNAME:-admin}"
  _AIRFLOW_WWW_USER_PASSWORD: "${_AIRFLOW_WWW_USER_PASSWORD:-admin}"

  # --- DAGSHUB ---
  DAGSHUB_USER: ${DAGSHUB_USER}
  AWS_ACCESS_KEY_ID: ${DAGSHUB_S3_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${DAGSHUB_S3_SECRET_ACCESS_KEY}

  # --- MLFLOW DU DAGSHUB ---
  MLFLOW_TRACKING_USERNAME: ${DAGSHUB_USER}
  MLFLOW_TRACKING_PASSWORD: ${DAGSHUB_S3_SECRET_ACCESS_KEY}

