# ici airflow:airflow sont des identifiants de connexion
AIRFLOW_CONN_POSTGRES_DEFAULT="postgres://airflow:airflow@postgres:5432/airflow"

# --- Airflow core ---
AIRFLOW__CORE__FERNET_KEY=${AIRFLOW_FERNET_KEY}

  # --- Webserver ---
  _AIRFLOW_WWW_USER_USERNAME: "${_AIRFLOW_WWW_USER_USERNAME:-admin}"
  _AIRFLOW_WWW_USER_PASSWORD: "${_AIRFLOW_WWW_USER_PASSWORD:-admin}"

  DAGSHUB_USER: ${DAGSHUB_USER}
  AWS_ACCESS_KEY_ID: ${DAGSHUB_S3_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${DAGSHUB_S3_SECRET_ACCESS_KEY}
  AWS_ENDPOINT_URL: "https://dagshub.com/s3"
  MLFLOW_TRACKING_USERNAME: ${DAGSHUB_USER}
  MLFLOW_TRACKING_PASSWORD: ${DAGSHUB_S3_SECRET_ACCESS_KEY}

