apiVersion: 1
policies:
    - orgId: 1
      receiver: webhook_alert_notification
      group_by:
        - grafana_folder
        - alertname
      # La toute première alerte,
      # on attend 10s avant de l'envoyer au webhook
      group_wait: 10s
      # Les alertes suivantes, 
      # on attend 20s avant de l'envoyer au webhook
      group_interval: 20s
      repeat_interval: 1h
