apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: evidently-config
    envs:
      - .env.config

resources:
  - pvc.yaml
  - ui/deployment.yaml
  - ui/service.yaml
  - monitoring/deployment.yaml
